# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 06 Nov 2011 17:33:08 +0000
*	@ALL	1
*	@user	2
*	@core	8
home	@user	1
wiki:dokuwiki	@user	1
wiki:nak12:home	@user	1
wiki:navigation	@ALL	1
wiki:plugins	@ALL	1
wiki:syntax	@user	1
talk:*	@user	1
